services:
  - type: worker
    name: cloudflare-bypasser-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
