name: Run Cloudflare Bypasser

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python app.py
